language: python

matrix:
  include:
    - os: linux
      sudo: false
      python: 2.7
    - os: linux
      sudo: false
      python: 3.5
    - os: osx
      language: generic

env:
  matrix:
    - GO_VERSION="1.2.2"
    - GO_VERSION="1.3"
    - GO_VERSION="1.3.1"
    - GO_VERSION="1.3.2"
    - GO_VERSION="1.3.3"
    - GO_VERSION="1.4"
    - GO_VERSION="1.4.1"
    - GO_VERSION="1.4.2"
    - GO_VERSION="1.4.3"
    - GO_VERSION="1.5"
    - GO_VERSION="1.5.1"
    - GO_VERSION="1.5.2"
    - GO_VERSION="1.5.3"
    - GO_VERSION="1.5.4"
    - GO_VERSION="1.6"
    - GO_VERSION="1.6.1"
    - GO_VERSION="1.6.2"
    - GO_VERSION="1.6.3"

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install python; fi

script:
  - ./gohere.py goroot --version=$GO_VERSION
  - mkdir gopath
  - GOPATH=$(pwd)/gopath goroot/bin/go get github.com/golang/example/hello
  - gopath/bin/hello
