language: python

matrix:
  include:
    - os: linux
      sudo: false
      python: 2.7
    - os: linux
      sudo: false
      python: 3.5
    - os: osx
      language: generic

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew unlink python
      brew install python
    fi
  - unset GOROOT # see https://github.com/travis-ci/travis-ci/issues/6388

script:
  # test default version
  - ./gohere.py goroot # --test
  - ./goroot/bin/go version
  - ./goroot/bin/go env
  - mkdir gopath
  - GOPATH=$(pwd)/gopath ./goroot/bin/go get -race github.com/starius/racesync
  - ./gopath/bin/racesync
  # test generation of scripts
  - ./gohere.py goroot --cache > run.sh
  - chmod +x run.sh
  - ./run.sh goroot-echo
  - ./goroot-echo/bin/go version
  - ./goroot-echo/bin/go env
  - mkdir gopath-echo
  - GOPATH=$(pwd)/gopath-echo ./goroot-echo/bin/go get -race github.com/starius/racesync
  - ./gopath-echo/bin/racesync
  # test all versions
  - ./test.py
