language: python

matrix:
  include:
    - os: linux
      sudo: false
      python: 2.7
    - os: linux
      sudo: false
      python: 3.5
    - os: osx
      language: generic

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install python; fi
  - unset GOROOT # see https://github.com/travis-ci/travis-ci/issues/6388

script:
  # test default version
  - ./gohere.py goroot --test
  - ./goroot/bin/go env
  - mkdir gopath
  - GOPATH=$(pwd)/gopath ./goroot/bin/go get github.com/golang/example/hello
  - ./gopath/bin/hello
  # test all versions
  - ./test.py
