language: python

matrix:
  include:
    - os: linux
      sudo: false
      python: 2.7
    - os: linux
      sudo: false
      python: 3.5
    - os: osx
      language: generic

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew unlink python
      brew install python
      brew install coreutils
      sudo ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum
    fi
  - unset GOROOT # see https://github.com/travis-ci/travis-ci/issues/6388

script:
  - ./build-sia.sh
